#!/usr/bin/env python3
"""Write .halo/spec/* from intake JSON in state. Stdlib only. Used by halo-spec-pack agents + CI."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_state(repo: Path) -> dict[str, Any]:
    p = repo / ".halo" / "state.json"
    if not p.exists():
        raise SystemExit(f"missing {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def bullets(items: list[Any], key: str | None = None) -> str:
    if not items:
        return "- (none)\n"
    lines = []
    for it in items:
        if isinstance(it, dict):
            title = it.get(key or "title") or it.get("name") or it.get("id") or str(it)
            extra = it.get("one_liner") or it.get("scope") or it.get("purpose") or ""
            lines.append(f"- **{title}**" + (f" — {extra}" if extra else ""))
        else:
            lines.append(f"- {it}")
    return "\n".join(lines) + "\n"


def write_specs(repo: Path) -> list[str]:
    state = load_state(repo)
    intake = state.get("intake") or {}
    name = state.get("product_name") or intake.get("product_name") or "Product"
    purpose = intake.get("purpose") or intake.get("core_purpose") or ""
    if isinstance(purpose, dict):
        purpose = purpose.get("text") or purpose.get("purpose") or json.dumps(purpose)
    features = intake.get("features") or []
    oos = intake.get("out_of_scope") or []
    users = intake.get("users") or {}
    success = intake.get("success_metric") or ""
    stack = intake.get("stack") or {}
    integrations = intake.get("integrations") or []
    data_model = intake.get("data_model") or {}
    design = intake.get("design") or {}
    milestones = intake.get("milestones") or []

    spec = repo / ".halo" / "spec"
    spec.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    def w(fname: str, body: str) -> None:
        path = spec / fname
        path.write_text(body.strip() + "\n", encoding="utf-8")
        written.append(str(path.relative_to(repo)))

    w(
        "PRD.md",
        f"""# {name}

> Generated by Halo {utc_now()}. Edit freely; re-lock when happy.

## What we're building

{purpose}

## Who it's for

{json.dumps(users, indent=2) if not isinstance(users, str) else users}

## Success metric

{success or "(define)"}

## In scope

{bullets(features)}

## Out of scope

{bullets(oos)}

## Integrations (summary)

{bullets(integrations, key="id")}

## Milestones (summary)

{bullets(milestones, key="name")}

## Open questions

- (add during review)
""",
    )

    w(
        "STACK.md",
        f"""# Stack — {name}

```json
{json.dumps(stack, indent=2)}
```

## Hosting guess

{(stack.get("hosting_guess") if isinstance(stack, dict) else None) or "preview host TBD (Vercel default for web)"}

## Repo layout target

Document expected top-level dirs after scaffold.
""",
    )

    entities = []
    if isinstance(data_model, dict):
        entities = data_model.get("entities") or data_model.get("models") or []
    elif isinstance(data_model, list):
        entities = data_model

    w(
        "DATA-MODEL.md",
        f"""# Data model — {name}

Conceptual. Not SQL.

{bullets(entities, key="name")}

## Relationships

{(data_model.get("relationships") if isinstance(data_model, dict) else "") or "(describe in review)"}
""",
    )

    w(
        "DESIGN.md",
        f"""# Design — {name}

```json
{json.dumps(design, indent=2)}
```

## Screens (draft)

Derive from features during review.
""",
    )

    w(
        "ARCHITECTURE.md",
        f"""# Architecture — {name}

## Boundaries

- Client UI
- API / server
- Data store
- External providers (see INTEGRATIONS.md)

## Deploy topology

- Dev / preview: per STACK hosting
- Prod: human promote only

## Non-goals

See PRD out of scope.
""",
    )

    integ_lines = ["# Integrations — " + name, ""]
    for it in integrations if isinstance(integrations, list) else []:
        if isinstance(it, dict):
            integ_lines.append(f"## {it.get('id') or it.get('provider')}")
            integ_lines.append(f"- Purpose: {it.get('purpose')}")
            integ_lines.append(f"- Provider: {it.get('provider')}")
            integ_lines.append(f"- Credentials: {', '.join(it.get('credentials') or []) or '—'}")
            integ_lines.append(f"- Milestones: {it.get('required_for_milestones')}")
            integ_lines.append("")
    if len(integ_lines) == 2:
        integ_lines.append("(none locked — readiness will still apply lifecycle baseline)")
    w("INTEGRATIONS.md", "\n".join(integ_lines))

    story_lines = [f"# Stories — {name}", ""]
    n = 1
    for feat in features if isinstance(features, list) else []:
        title = feat.get("title") if isinstance(feat, dict) else str(feat)
        sid = f"S{n:03d}"
        story_lines.extend(
            [
                f"### {sid} — {title}",
                "- **Priority**: high",
                "- **Milestone**: M1",
                "- **Status**: pending",
                "- **Acceptance criteria**:",
                f"  - [ ] User can complete primary flow for: {title}",
                "  - [ ] Covered by automated test or documented manual probe",
                "",
            ]
        )
        n += 1
    w("STORIES.md", "\n".join(story_lines) if n > 1 else f"# Stories — {name}\n\n(none yet)\n")

    ms_lines = [f"# Milestones — {name}", ""]
    for m in milestones if isinstance(milestones, list) else []:
        if not isinstance(m, dict):
            continue
        ms_lines.extend(
            [
                f"## M{m.get('n', '?')} — {m.get('name')}",
                f"- Slug: `{m.get('slug')}`",
                f"- Scope: {m.get('scope')}",
                f"- Done when: {m.get('done_when_draft') or m.get('done_when') or 'TBD'}",
                f"- Depends on: {m.get('depends_on')}",
                "",
            ]
        )
    if len(ms_lines) == 2:
        ms_lines.append("(define milestones in intake)")
    w("MILESTONES.md", "\n".join(ms_lines))

    w(
        "READINESS.md",
        f"""# Readiness — {name}

Run after lock:

```bash
python3 <HALO_SYSTEM>/python/halo_readiness.py --repo . --write
```

This file is overwritten by the readiness tool with the live checklist.
""",
    )

    # mark drafting
    state["spec_status"] = state.get("spec_status") if state.get("spec_status") == "locked" else "ready_for_review"
    if state.get("phase") not in ("readiness", "scaffold", "build"):
        state["phase"] = "spec_review"
    state["updated_at"] = utc_now()
    (repo / ".halo" / "state.json").write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    (repo / ".halo" / "baton.md").write_text(
        "# Baton\n- Phase: spec_review\n- Next: human reviews .halo/spec/; then "
        "`python3 …/halo_state.py lock-specs --repo .` then readiness\n",
        encoding="utf-8",
    )
    # machine feature list (done tracking)
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from halo_features import sync_from_stories
        from halo_progress import append as progress_append

        sync_from_stories(repo)
        progress_append(repo, "spec_pack_written", {"files": len(written)})
    except Exception:
        pass
    return written


def main() -> None:
    p = argparse.ArgumentParser(prog="halo_spec_write")
    p.add_argument("--repo", default=".")
    args = p.parse_args()
    written = write_specs(Path(args.repo).resolve())
    print(json.dumps({"ok": True, "files": written}, indent=2))


if __name__ == "__main__":
    main()
